import { useSession } from 'next-auth/client'
import { Grid, GridItem, Center, Text, Stack, Box } from "@chakra-ui/react"
import { ModuleCard } from '../components/moduleCard'

/* 
export async function getServerSideProps() {
  const res = await fetch(process.env.NEXTAUTH_URL+'/api/auth/session')
  const data = await res.json()

  console.log(res)
  console.log(data)
  return { props: { data } }
}
*/

export async function getServerSideProps(context) {

  const res_user = await fetch(process.env.NEXTAUTH_URL+'/api/v2/user', {
    method: "POST",
    headers: {
      Cookie: context.req.headers.cookie
    }
  })

  const res_module = await fetch(process.env.NEXTAUTH_URL+'/api/v2/module', {
    method: "POST",
    headers: {
      Cookie: context.req.headers.cookie,
    }
  })

  const data_user = await res_user.json()
  const data_module = await res_module.json()
  
  //console.log(data)

  if (res_user.status!=200 && res_module.status!=200) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      data: {
        modules: data_module.modules,
        users: data_user,
        config:{
          report: true
        }
      }
    }, 
  }
}

export default function Home({data}){
  const [ session ] = useSession()

  var modulosDisponiveis = []
  
  data.users.modulos.forEach(element => {

    //for(var i=0; i<data.modules)
    modulosDisponiveis.push(
      <div className="ModuleCard">
        <ModuleCard modulo={element} modulos={data.modules}/>
      </div>
    );

  });

  return <>
    <Center>
      <Stack spacing={3} marginTop={6}>
        <Text fontSize="2xl" as="b">Módulos Disponíveis</Text>
      </Stack>
    </Center>
    <Grid templateColumns="repeat(5, 1fr)" gap={6} m={4}>
        {modulosDisponiveis}
    </Grid>
  </>
}

/*
export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
*/